# Generated by Django 4.2.4 on 2024-03-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psql_journal', '0002_transaction_transactionrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoInputFields',
        ),
    ]
